services:
  backend:
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    deploy:
      restart_policy:
          condition: on-failure
          delay: 2s
          max_attempts: 3
          window: 120s  

  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
          condition: on-failure
          delay: 2s
          max_attempts: 3
          window: 120s
      
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    deploy:
      restart_policy:
          condition: on-failure
          delay: 2s
          max_attempts: 3
          window: 120s
